name: "1 Hello world"

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  say_hello_job:
    runs-on: ubuntu-latest  # The runner environment (Ubuntu in this case)

    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"

  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Number
        run: |
          echo "1st"
          echo "Workflow"

      - name: Echo Name
        run: echo "1 Hello world"