#https://github.com/misohu/github-actions-course/blob/main/.github/workflows/007_passing_files.yaml

name: "7 Passing files in artifacts"

on: workflow_dispatch

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4

      - name: "Install node"
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: "Run tests"
        run: |
          cd fe
          npm test
          ls -la ${{ github.workspace }}/fe
